package com.daveace.qrnavigationapp.ui.theme

import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF005FAE)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD4E3FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001C3A)
val md_theme_light_secondary = Color(0xFF4858A9)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFDEE1FF)
val md_theme_light_onSecondaryContainer = Color(0xFF001159)
val md_theme_light_tertiary = Color(0xFF006399)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFCDE5FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001D32)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFCFCFF)
val md_theme_light_onBackground = Color(0xFF001D31)
val md_theme_light_surface = Color(0xFFFCFCFF)
val md_theme_light_onSurface = Color(0xFF001D31)
val md_theme_light_surfaceVariant = Color(0xFFE0E2EC)
val md_theme_light_onSurfaceVariant = Color(0xFF43474E)
val md_theme_light_outline = Color(0xFF74777F)
val md_theme_light_inverseOnSurface = Color(0xFFE7F2FF)
val md_theme_light_inverseSurface = Color(0xFF003351)
val md_theme_light_inversePrimary = Color(0xFFA5C8FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF005FAE)
val md_theme_light_outlineVariant = Color(0xFFC3C6CF)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFA5C8FF)
val md_theme_dark_onPrimary = Color(0xFF00315E)
val md_theme_dark_primaryContainer = Color(0xFF004785)
val md_theme_dark_onPrimaryContainer = Color(0xFFD4E3FF)
val md_theme_dark_secondary = Color(0xFFB9C3FF)
val md_theme_dark_onSecondary = Color(0xFF152778)
val md_theme_dark_secondaryContainer = Color(0xFF2F4090)
val md_theme_dark_onSecondaryContainer = Color(0xFFDEE1FF)
val md_theme_dark_tertiary = Color(0xFF95CCFF)
val md_theme_dark_onTertiary = Color(0xFF003352)
val md_theme_dark_tertiaryContainer = Color(0xFF004A75)
val md_theme_dark_onTertiaryContainer = Color(0xFFCDE5FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001D31)
val md_theme_dark_onBackground = Color(0xFFCDE5FF)
val md_theme_dark_surface = Color(0xFF001D31)
val md_theme_dark_onSurface = Color(0xFFCDE5FF)
val md_theme_dark_surfaceVariant = Color(0xFF43474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC3C6CF)
val md_theme_dark_outline = Color(0xFF8D9199)
val md_theme_dark_inverseOnSurface = Color(0xFF001D31)
val md_theme_dark_inverseSurface = Color(0xFFCDE5FF)
val md_theme_dark_inversePrimary = Color(0xFF005FAE)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFA5C8FF)
val md_theme_dark_outlineVariant = Color(0xFF43474E)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF028BFA)